### ISSUE TITLE
Localized styles not supported for widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#152]
In dashboards the ENV parameter for localized styles is not currently supported.

The parameter **localizedLayerStyles**

![image](https://user-images.githubusercontent.com/1280027/84059146-657e2b00-a9ba-11ea-88d6-979e97333ee5.png)
 
must be supported in catalog config on DashboardEditor [here ](https://github.com/geosolutions-it/MapStore2-C028/blob/1bfabc006391860a30916a33a26acce722f9261f/localConfig.json#L893) so that, if set to true, all layers added from the catalog tool in dashboard editor can have the ENV query parameter for each getmap and getlegendgraphic request by default.

Then there must be the possibility to activate/deactivate it per layer inside the layers settings (as it currently is inside the viewer)

![image](https://user-images.githubusercontent.com/1280027/84061885-f8b95f80-a9be-11ea-9924-52873bfa9712.png)

**Comment by tdipisa** [comment]
There is still a problem here:

as soon as you change language the **Use localized styles** in layer settings change state (from true to false), therefore the GetMap requests don't include the ENV param

There is also an issue in legend widget where the **Language** parameter is not currently supported

![image](https://user-images.githubusercontent.com/1280027/84487381-f563f380-ac9e-11ea-976f-1c41a51a0b9c.png)

**Comment by MV88** [comment]
I noticed that the map preview has no localized layers too, so maybe the env paramater is not passed to it.

the problem with reset of the localized styles layer flag when you change locale is because that dashboard had initially set the flag to false, and when changing locale it reloads the dashboard. 
this does not happen with new dashboards since they have the flag set to true from the start

**Comment by gitcontributor** [comment]
I've fixed bug with LegendPriview in https://github.com/geosolutions-it/MapStore2/pull/5477
Speaking of the 1st problem. I don't think this is a problem because, as matteo said, changing the locale reloads the page. Only widget changes are saved in the presented gif, but not the dashboard itself, so before the change of locale the dashboard need to be saved.

**Comment by MV88** [comment]
@gitcontributor you still need to fix the map preview in the widget wizard

**Comment by tdipisa** [comment]
@MV88 @gitcontributor ok about the following:

>the problem with reset of the localized styles layer flag when you change locale is because that dashboard had initially set the flag to false, and when changing locale it reloads the dashboard.
this does not happen with new dashboards since they have the flag set to true from the start

**Comment by gitcontributor** [comment]
@tdipisa @MV88 fixed related problems
